tinymce.addI18n('en_US', {
    "Cut": "Cut",
    "Header 2": "Header 2",
    "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.",
    "Div": "Division",
    "Paste": "Paste",
    "Close": "Close",
    "Font Family": "Font Family",
    "Pre": "Pre",
    "Align right": "Align Right",
    "New document": "New Document",
    "Blockquote": "Blockquote",
    "Numbered list": "Numbered List",
    "Increase indent": "Increase Indent",
    "Formats": "Formats",
    "Headers": "Headers",
    "Select all": "Select All",
    "Header 3": "Header 3",
    "Blocks": "Blocks",
    "Undo": "Undo",
    "Strikethrough": "Strike-Through",
    "Bullet list": "Bullet List",
    "Header 1": "Header 1",
    "Superscript": "Supercript",
    "Clear formatting": "Clear Formatting",
    "Font Sizes": "Font Sizes",
    "Subscript": "Subscript",
    "Header 6": "Header 6",
    "Redo": "Redo",
    "Paragraph": "Paragraph",
    "Ok": "OK",
    "Bold": "Bold",
    "Code": "Code",
    "Italic": "Italic",
    "Align center": "Align Center",
    "Header 5": "Header 5",
    "Decrease indent": "Decrease Indent",
    "Header 4": "Header 4",
    "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.",
    "Underline": "Underline",
    "Cancel": "Cancel",
    "Justify": "Justify",
    "Align justify": "Align Justify",
    "Inline": "Inline",
    "Copy": "Copy",
    "Align left": "Align Left",
    "Visual aids": "Visual Aids",
    "Lower Greek": "Lower Greek",
    "Square": "Square",
    "Default": "Default",
    "Lower Alpha": "Lower Alpha",
    "Circle": "Circle",
    "Disc": "Disc",
    "Upper Alpha": "Upper Alpha",
    "Upper Roman": "Upper Roman",
    "Lower Roman": "Lower Roman",
    "Name": "Name",
    "Anchor": "Anchor",
    "You have unsaved changes are you sure you want to navigate away?": "You have unsaved changes are you sure you want to navigate away?",
    "Restore last draft": "Restore Last Draft",
    "Special character": "Special Character",
    "Source code": "Source Code",
    "Right to left": "Right to Left",
    "Left to right": "Left to Right",
    "Emoticons": "Emoticons",
    "Robots": "Robots",
    "Document properties": "Document Properties",
    "Title": "Title",
    "Keywords": "Keywords",
    "Encoding": "Encoding",
    "Description": "Description",
    "Author": "Author",
    "Fullscreen": "Full Screen",
    "Horizontal line": "Horizontal Line",
    "Horizontal space": "Horizontal Space",
    "Insert\/edit image": "Insert\/Edit Image",
    "General": "General",
    "Advanced": "Advanced",
    "Source": "Source",
    "Border": "Border",
    "Constrain proportions": "Constrain Proportions",
    "Vertical space": "Vertical Space",
    "Image description": "Image Description",
    "Style": "Style",
    "Dimensions": "Dimensions",
    "Insert image": "Insert Image",
    "Insert date\/time": "Insert Date\/Time",
    "Remove link": "Remove Link",
    "Url": "URL",
    "Text to display": "Text to Display",
    "Anchors": "Anchors",
    "Insert link": "Insert Link",
    "New window": "New Window",
    "None": "None",
    "The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?",
    "Target": "Target",
    "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?",
    "Insert\/edit link": "Insert\/Edit Link",
    "Insert\/edit video": "Insert\/Edit Video",
    "Poster": "Poster",
    "Alternative source": "Alternative Source",
    "Paste your embed code below:": "Paste your embed code below:",
    "Insert video": "Insert Video",
    "Embed": "Embed",
    "Nonbreaking space": "Non-Breaking Space",
    "Page break": "Page Break",
    "Paste as text": "Paste as Text",
    "Preview": "Preview",
    "Print": "Print",
    "Save": "Save",
    "Could not find the specified string.": "Could not find the specified string.",
    "Replace": "Replace",
    "Next": "Next",
    "Whole words": "Whole Words",
    "Find and replace": "Find and Replace",
    "Replace with": "Replace With",
    "Find": "Find",
    "Replace all": "Replace All",
    "Match case": "Match Case",
    "Prev": "Prev",
    "Spellcheck": "Spell-Check",
    "Finish": "Finish",
    "Ignore all": "Ignore All",
    "Ignore": "Ignore",
    "Insert row before": "Insert Row Before",
    "Rows": "Rows",
    "Height": "Height",
    "Paste row after": "Paste Row After",
    "Alignment": "Alignment",
    "Column group": "Column Group",
    "Row": "Row",
    "Insert column before": "Insert Column Before",
    "Split cell": "Split Cell",
    "Cell padding": "Cell Padding",
    "Cell spacing": "Cell Spacing",
    "Row type": "Row Type",
    "Insert table": "Insert Table",
    "Body": "Body",
    "Caption": "Caption",
    "Footer": "Footer",
    "Delete row": "Delete Row",
    "Paste row before": "Paste Row Before",
    "Scope": "Scope",
    "Delete table": "Delete Table",
    "Header cell": "Header Cell",
    "Column": "Column",
    "Cell": "Cell",
    "Header": "Header",
    "Cell type": "Cell Type",
    "Copy row": "Copy Row",
    "Row properties": "Row Properties",
    "Table properties": "Table Properties",
    "Row group": "Row Group",
    "Right": "Right",
    "Insert column after": "Insert Column After",
    "Cols": "Cols",
    "Insert row after": "Insert Row After",
    "Width": "Width",
    "Cell properties": "Cell Properties",
    "Left": "Left",
    "Cut row": "Cut Row",
    "Delete column": "Delete Column",
    "Center": "Center",
    "Merge cells": "Merge Cells",
    "Insert template": "Insert Template",
    "Templates": "Templates",
    "Background color": "Background Color",
    "Border color": "Border Color",
    "Text color": "Text Color",
    "Show blocks": "Show Blocks",
    "Show invisible characters": "Show Invisible Characters",
    "Words: {0}": "Words: {0}",
    "Insert": "Insert",
    "Delete": "Delete",
    "File": "File",
    "Edit": "Edit",
    "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help",
    "Tools": "Tools",
    "View": "View",
    "Table": "Table",
    "Format": "Format",
    "No color": "No Color",
    "Marker": "Marker",
    "Keyboard": "Keyboard",
    "Button": "Button"
});